### ISSUE TITLE
remove snp for phylogenesis

### ISSUE THREAD

**Issue by aspitaleri** [ngs-fzb/MTBseq_source#62]
Hi there,
in the manual it says:
" --window This OPTION is used in TBamend. By default, the OPTION is set to 12. The OPTION sets a window size in which the algorithm scans for the occurrence of multiple variants within the same sample. If more than one variant occurs within this window in the same sample, the positions will be excluded."
Just to make sure that I understood well:
ACC**C**GCG**T**CGTGCTGCGCTC**G**GGTTCCAATGCGTT**A**
you will keep **G** and **A** only, removing **C** and **T**, right? basically left-right more than 12nt.
Best

**Comment by TaKohl** [comment]
Hello, 
yes, if I am counting correctly in your example, that is exactly what happens. The basic functionality is to slide a 12 bp window over the sequence and if there are at least two variants detected within that window (and for the same sample), all variant positions within that window will be discarded from the output file filtered for phylogenetic analysis.
Just to be clear, all detected variants will of course be included in the main result file.
best, 
Thomas

**Comment by aspitaleri** [comment]
Thanks Tomas.
So you remove them during the sliding process as follow:

M	3	C	A	
M	5	G	T
M	15	G	A
M	33	C	G
M	43	T	C
M	56	A	T
M	58	C	G
M	101	T	G

you remove position **3, 5, 33, 43, 56, 58** and keep only **15 and 101**, right? 15 position is kept because we removed 5 from the list, right?  So basically you are shifting the variant array by two if the two elements are in the 12bp window. 
Thanks!

**Comment by TaKohl** [comment]
Hello, 
yes, from your example the output for the phylogenetic analysis should be keeping positions 15 and 101 and dropping the rest. However, it does not work by shifting variant arrays, there is actually a subroutine processing the data for each sample and then marking those positions with neighbors within 12 bp for later filtering. 

Also, please keep in mind that in the default implementation the window filtering step takes place after the first filtering step has already limited the positions to valid SNP or WT allele calls only. The reason is of course partly to avoid dropping positions because of (due to whatever reasons) weak variant calls.

It can actually be a very interesting discussion on when and how to do this filtering step, or whether to do it at all. You can of course just limit the window size or modify the underlying code if you would like to change this feature.
best,
Thomas

**Comment by TaKohl** [comment]
... and a correction, position 15 would of course also be filtered since it falls within a 12 bp window with position 5. 
Thomas

**Comment by aspitaleri** [comment]
ah okay -  clear. that make sense better.
